data:extend {
  {
    type = "fluid",
    name = "liquid-mercury",
    icon = "__hydrargyros__/graphics/fluids/fluid-droplet-mercury.png",
    subgroup = "fluid",
    order = "n[new-fluid]-b[fluids]",
    default_temperature = -40,
    max_temperature = 360,
    heat_capacity = "140J",
    base_color = {215, 204, 184},
    flow_color = {215, 204, 184},
    auto_barrel = false,
    hidden = false,
  },
  {
    type = "fluid",
    name = "magnesium-chloride-brine",
    icon = "__hydrargyros__/graphics/fluids/fluid-droplet-magnesium-chloride-brine.png",
    subgroup = "fluid",
    order = "n[new-fluid]-a[fluids]",
    default_temperature = -50,
    max_temperature = 150,
    heat_capacity = "4000J",
    base_color = {81, 123, 7},
    flow_color = {81, 123, 7},
    auto_barrel = false,
    hidden = false,
  },
  {
    type = "fluid",
    name = "fluid-copper-mercury-amalgam",
    icon = "__hydrargyros__/graphics/fluids/fluid-copper-mercury-amalgam.png",
    subgroup = "fluid",
    order = "n[new-fluid]-c[fluids]",
    default_temperature = -40,
    max_temperature = 300,
    heat_capacity = "200J",
    base_color = {212, 143, 96},
    flow_color = {212, 143, 96},
    auto_barrel = false,
    hidden = false,
  },
  {
    type = "fluid",
    name = "fluid-thermite-gel",
    icon = "__hydrargyros__/graphics/fluids/fluid-thermite-gel.png",
    subgroup = "fluid",
    order = "n[new-fluid]-f[fluids]",
    default_temperature = 50,
    max_temperature = 300,
    heat_capacity = "1500J",
    base_color = {86, 73, 22, 100},
    flow_color = {86, 73, 22, 100},
    auto_barrel = false,
    hidden = false,
  },
  {
    type = "fluid",
    name = "gas-mercury-vapor",
    icon = "__hydrargyros__/graphics/fluids/gas-mercury-vapor.png",
    subgroup = "fluid",
    order = "n[new-fluid]-d[fluids]",
    default_temperature = -40,
    max_temperature = 1000,
    heat_capacity = "120J",
    base_color = {122, 122, 122, 100},
    flow_color = {122, 122, 122, 100},
    auto_barrel = false,
    hidden = false,
  },
  {
    type = "fluid",
    name = "molecule-carbon-dioxide",
    icon = "__hydrargyros__/graphics/fluids/molecule-carbon-dioxide.png",
    subgroup = "fluid",
    order = "n[new-fluid]-q[fluids]",
    default_temperature = -125,
    max_temperature = 10000,
    heat_capacity = "850J",
    base_color = {37, 37, 37},
    flow_color = {37, 37, 37},
    auto_barrel = false,
    hidden = false,
  },  
  {
    type = "fluid",
    name = "molecule-chlorine",
    icon = "__hydrargyros__/graphics/fluids/molecule-chlorine.png",
    subgroup = "fluid",
    order = "n[new-fluid]-o[fluids]",
    default_temperature = -110,
    max_temperature = 2000,
    heat_capacity = "480J",
    base_color = {49, 162, 96},
    flow_color = {49, 162, 96},
    auto_barrel = false,
    hidden = false,
  },
  {
    type = "fluid",
    name = "molecule-hydrochloric-acid",
    icon = "__hydrargyros__/graphics/fluids/molecule-hydrochloric-acid.png",
    subgroup = "fluid",
    order = "n[new-fluid]-p[fluids]",
    default_temperature = -30,
    max_temperature = 75,
    heat_capacity = "2500J",
    base_color = {107, 180, 133},
    flow_color = {107, 180, 133},
    auto_barrel = false,
    hidden = false,
  },      
  {
    type = "fluid",
    name = "molecule-hydrogen",
    icon = "__hydrargyros__/graphics/fluids/molecule-hydrogen.png",
    subgroup = "fluid",
    order = "n[new-fluid]-r[fluids]",
    default_temperature = -250,
    max_temperature = 2000,
    heat_capacity = "14000J",
    base_color = {194, 121, 141, 100},
    flow_color = {194, 121, 141, 100}, --Its Pink Cause Its Pink In ONI
    auto_barrel = false,
    hidden = false,
  },      
  {
    type = "fluid",
    name = "molecule-methanol",
    icon = "__hydrargyros__/graphics/fluids/molecule-methanol.png",
    subgroup = "fluid",
    order = "n[new-fluid]-s[fluids]",
    default_temperature = -95,
    max_temperature = 40,
    heat_capacity = "2500J",
    base_color = {181, 181, 181, 20},
    flow_color = {181, 181, 181, 20},
    auto_barrel = false,
    hidden = false,
  },    
  {
    type = "fluid",
    name = "fluid-calcium-brine",
    icon = "__hydrargyros__/graphics/fluids/fluid-calcium-brine.png",
    subgroup = "fluid",
    order = "n[new-fluid]-e[fluids]",
    default_temperature = -55,
    max_temperature = 120,
    heat_capacity = "4000J",
    base_color = {225, 215, 197},
    flow_color = {225, 215, 197},
    auto_barrel = false,
    hidden = false,
  },      
}